  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
#      - PLEX_CLAIM= #optional
    volumes:
      - ./volumes/plex/library:/config
      - ./TVseries:/tv
      - ./Movies:/movies
    restart: unless-stopped
